### ISSUE TITLE
Why the needed of a "resp" object?

### ISSUE THREAD

**Issue by shinayser** [rknell/alfred#1]
Since dart has built in Futures feature, why the lambda passed to "get", "post", etc, need a "resp" paramether? Why just not simply a lambda with the signature: `Future<Response> Function(Request)` ?

**Comment by rknell** [comment]
hey @shinayser 

A couple of reasons:

The first is for ease of use in getting users to adopt the framework. I know thats not a great "reason" but if you can quickly pick it up and reason about it from an expressjs background, then that helps. The more adoption, the better the support.

The second and main reason I didn't kill it altogether is flexibility and robustness out of the box. While Alfred provides an easy way to return a future for most use cases, having low level access to [HttpResponse](https://api.dart.dev/stable/2.10.5/dart-io/HttpResponse-class.html) object ensures you will never get stuck unable to do something if the framework doesn't support it.

Great question

**Comment by shinayser** [comment]
Interesting point...
 
 But by the perspective of ease of use, you could create a lot of pre-built-in responses like: "ServerErrorResponse", "NotFoundResponse", etc that could make the library easier to use and more "dart-like".

But this is just my opinion. Best regards =)

**Comment by rknell** [comment]
Right now you really don't have to use the res object for anything.

At any point if you want to throw an error you can call

```
route(req, res)=> throw AlfredException(400, {"message": "invalid request"});
```

This will bubble up and the statuscode, body and headers will be calculated.

If it's just a JSON response or even a binary file you just return them like so:

```dart
main() async {
  final app = Alfred();

  app.get("/text", (req, res)=> "Text response");

  app.get("/json", (req, res)=> {"json_response": true});

  app.get("/file", (req, res) => File("thefile.jpg"));

  await app.listen(port: 6565); //Listening on port 6565 
}
```
