### ISSUE TITLE
Flutter Web HTTP Error: XMLHttpRequest error

### ISSUE THREAD

**Issue by jrheisler** [rknell/alfred#107]
I have been using Alfred to serve up files to a flutter web app without issue on windows (both flutter web and Alfred server). But, if I try to add HTTP calls from the flutter web app the Alfred server gets the call, but in Flutter Web it errors our Error: XMLHttpRequest.

Is this because of a CORS issue? Is there a setting I need, a CORS middleware setting?

**Comment by seceba** [comment]
Hey, can you try  server.all('*', cors(origin: '*'));

**Comment by jrheisler** [comment]
Same.

Flutter code:
Future<void> getAlfred() async{

  final client = http.Client();

  try {
    print(await client.get(Uri.parse('http://localhost:3000/status'),     
        ));
  } finally {
    client.close();
  } 
}

Alfred code:
void main() async {
  final app = Alfred();
  app.all('', cors(origin: ''));
  app.get('/file/:name', (req, res) {
    print('9 - ${req.params['name']}');
    res.setDownload(filename: '${req.params['name']}');
    return File('${req.params['name']}');
  });
  app.get('/status', (req, res) {
    print('request status');
    return 'Server Online';
  });

  await app.listen(); //Listening on port 3000
}

Print out:
2022-09-15 14:43:54.030013 - info - HTTP Server listening on port 3000
2022-09-15 14:43:59.872688 - info - GET - /status
request status

thank you!!!

**Comment by jrheisler** [comment]
Another clue I wanted to share with you. I pointed out above that I've been using Alfred to serve files to a flutter web app, both on Windows 10. But, if I run the web app on a mac, and the Alfred server on the mac, the web app doesn't get the files (mp3, and png)

The flutter web app uses  Image.network('http://localhost:3000/file/$name_of_the_file')

So maybe it is some sort of CORS thing, and Windows doesn't stop it?

**Comment by rknell** [comment]
Hey @jrheisler 

Alfred was developed on a Mac so should definitely serve files correctly. 

I don't have my computer with me at the moment to look into it, but I'm not sure it's pointing to a file correctly.

You can rule out CORS issues by trying to navigate directly to the file. I also don't recall cors being an issue for files, but you can't usually grab a http resource from a https one which could be an issue.

**Comment by jrheisler** [comment]
I'm not sure it would work on windows and not a mac. I'm cracking out my old macbook this weekend to debug it on the mac. Thanks!!!

**Comment by rknell** [comment]
Oh sorry I thought you said it worked on windows but stopped working when you moved to Mac. Do it should definitely work on windows too

**Comment by jrheisler** [comment]
Sorry about the confusion. As for it working on the Mac, it actually works the same as on Windows. I was running it wrong. But, the error for http requests are the same. No error from the Alfred app,  same error from the flutter app running on a Mac Error: XMLHttpRequest.

**Comment by rknell** [comment]
Ahh, it look like it's probably a cors problem.

In the docs try applying cors to all routes and I bet that will solve your problem

**Comment by jrheisler** [comment]
This doesn't work, should it be different?

void main() async {
  final app = Alfred();
  app.all('*', cors(origin: ''));
  app.get('/file/:name', (req, res) {
  
    res.setDownload(filename: '${req.params['name']}');
  
    final f = File('${req.params['name']}');
    return f;
  });
  
  await app.listen(); //Listening on port 3000
}

**Comment by rknell** [comment]
That wont fix the cors bit because you are saying the origin is an empty string.

Just try not specifying the origin like this:

app.all('*', cors());

**Comment by jrheisler** [comment]
That works like a champ, thanks!

**Comment by jrheisler** [comment]
When I moved the server off my local machine, and wasn't calling it as localhost, the problem resurfaced, but, only when built and deployed.

I was adding Web Sockets, using the simple chat client you have in your examples. It worked great localhost or on another machine in my network. But, in the flutter web app if I build and deploy it, it only works on localhost:
flutter build web  --release
firebase deploy

and run from the web nothing works

but if I:
flutter run -d chrome --release

Everything works. Localhost, another IP, it all works. 

I must be missing something, and I really apologize for bugging you.

Thanks!!!

**Comment by seceba** [comment]
Hello,

Can you try using the port when using WebSocket?

Like this ws://domain.com:3000/websocket/chatid

I had a similar situation, but mine was a proxy_sey_header problem related to nginx. With a little research, I was able to develop an active chat application.

**Comment by jrheisler** [comment]
Hi, I am using the port:

serverAddress = 192.168.0.110;

ws://$serverAddress:3000/ws

Websocket doesn't work, nor does Image.network...

It all works when the server is on the same machine, or if I use it flutter run -d chrome --release, then it will work no matter where the server is.

It doesn't error, it just hangs.
