### ISSUE TITLE
Router callback handlers are not async-safe

### ISSUE THREAD

**Issue by daniel-v** [rknell/alfred#112]
Let met try to explain what I mean by "async-safe".

My expectation for serving a page is that the response is

1. returned/written only when all async computation that has finished for a given request finished running
2. can capture any all all async computation exceptions before a response would be returned to the browser

Let me demonstrate it:

```dart
import 'dart:async';
import 'dart:io';
import 'dart:math';

import 'package:alfred/alfred.dart';

final rnd = Random.secure();

void main() async {
  final app = Alfred(
    onInternalError: (req, resp) {
      stderr.writeln('Internal error occured for ${req.store.get('rid')}');
    },
    logLevel: LogType.debug,
  );
  app.all('*', (req, res) {
    final id = (rnd.nextInt(8999999) + 1000000).toRadixString(36);
    print('Request ID: $id');
    req.store.set('rid', id);
  });

  app.get('/err', (req, res) async {
    Future.delayed(Duration(seconds: 5), () async {
      throw 'ASYNC ERR';
    });
    return 'Returned before all request related computation finished: ${req.store.get('rid')}';
  });

  app.printRoutes();
  await app.listen();

  print('Server is listening on http://localhost:3000');
}
```

In this very specific instance, I'd expect the following to happen:

1. `onInternalError` catches `ASYNC ERR` - it does not
2. before `/err`'s return value would be written (sent back to browser), delayed future's result is awaited
3. server does not crash - it does

While this can be worked around and lint rules set up (unawaited_futures eg.), it is very likely that eventually some random future will crash the server which will be very hard to track down without the capability of catching it.

A solution I saw being used is that _all_ code that works on requests or responses are ran within it's own error zone (`runZonedGuarded`). With a custom `Zone` implementaiton, you could even give super useful warning messages that request returned before all futures would have completed (similar to how test package tracks them).

This would give me a sense of security.

**Comment by daniel-v** [comment]
This is a quick and dirty prototype to demonstrate the direction I'm thinking: 

```patch
diff --git a/lib/src/alfred.dart b/lib/src/alfred.dart
index b3995d2..f582ea8 100644
--- a/lib/src/alfred.dart
+++ b/lib/src/alfred.dart
@@ -328,8 +328,19 @@ class Alfred with Router {
           /// catching an error. This fixes it and its in tests, so if you can
           /// remove it and all the tests pass, cool beans.
           // try {
-          await _handleResponse(
-              await match.route.callback(request, request.response), request);
+
+          await _handleResponse(await runZonedGuarded(() async {
+            FutureOr callbackResult = await match.route.callback(request, request.response);
+            return callbackResult;
+          }, (error, stack) {
+            // FIXME: this only fixes server crash but does not prevent writing response before all futures would
+            // complete. For that, a custom zone is needed.
+            logWriter(() => 'Async ERROR: $error', LogType.error);
+            logWriter(() => '$stack', LogType.error);
+          }), request);
+
+          // await _handleResponse(
+          //     await match.route.callback(request, request.response), request);
           // } catch (e, s) {
           //   logWriter(() => match.route.toString(), LogType.error);
           //   logWriter(() => e, LogType.error);
```

**Comment by daniel-v** [comment]
@rknell do you think this is something worth looking into?

**Comment by rknell** [comment]
I think so, the proposed solution probably is all that's needed for now. Having people write headers twice etc is hard to police but all server crashes should be prevented if possible

**Comment by daniel-v** [comment]
> Having people write headers twice etc is hard to police

@rknell  Could you elaborate on the relevance of this to this issue? I'm not certain how this comes into play, I'd like to make sure that I foresee this pitfall before diving deeper.

**Comment by rknell** [comment]
Let's say you manually set the status code to 200 and then you write some data to the client, even a single byte, that status code gets sent. Then if you have some error which gets thrown and you try to change the status code to 500 an error will throw because the headers have already been written.

If you are just using the simple returns for things like Json you will be fine.

**Comment by daniel-v** [comment]
Right! 

Yeah, that occured to me too. Without bigger changes as to how requests are handled in Alfred, it is tough to handle the situation you mentioned.

Ultimately, however, it is still better to have the capability of erroring in logs than crashing. Coders can take appropriate action in that case.

**Comment by rknell** [comment]
It shouldn't crash the server in that case though, there are tests for it
and everything

**Comment by rknell** [comment]
Sorry I completely forgot about this ticket until another one came up that i'm suspicious is caused by what you were trying to fix!

I implemented it further up right at the very first stage of the request in an attempt to catch any possible errors in the users code and prevent any breaking changes. Thanks for the feedback. If you think i've done this the wrong way happy for any guidance.
