### ISSUE TITLE
Flutter web insecure content

### ISSUE THREAD

**Issue by jrheisler** [rknell/alfred#115]
Ryan, I'm not sure where to put this, but I wanted to share it with any users of Alfred using flutter web to connect. If your alfred server is not local and not providing ssl, https, Flutter released web aps will not support it. Your await http.get(...) will just hang.

Your flutter app will work in development, and while using localhost. But, once you go to another machine the browser takes over. 

The fix is to either, get a cert, or change your browser's settings for your app to enable mixed content (secure and unsecure). You have a good example of using a cert, but to change your browsers settings google: browser allow insecure content

**Comment by rknell** [comment]
Hey Jeff,

Do you have some official guide / documentation about this? If so I will
add it to the docs.
