### ISSUE TITLE
Request-bound storage

### ISSUE THREAD

**Issue by felixblaschke** [rknell/alfred#16]
In certain scenarios we want middleware to pass data down the pipeline. For example if you have middleware that resolves credential information based on JWT-style token.

Here is an example:
```dart
import 'dart:async';
import "dart:io";

import "package:alfred/alfred.dart";

FutureOr credentialResolver(HttpRequest req, HttpResponse res) async {
  var token = req.headers.value('X-SESSION-TOKEN');
  var user = await authority.tokenToUser(token);
  req.store.set('user', user);
}

Future<void> main() async {
  final app = Alfred();

  app.all('*', credentialResolver);

  app.get("/some/path", (req, res) async {
    var user = req.store.get<User>('user');
    return "Hello ${user.name}";
  });

  await app.listen();
}
```
This can also be used for performance measurements or general tracking.

This mechanism can also be used to address issue https://github.com/rknell/alfred/issues/14

If such feature comes we need an option to continue pipeline processing although the response writer is closed, i.e. tracking middleware. A flag like `req.isDone` comes handy to check this.

**Comment by rknell** [comment]
Implemented a version of this in 0.1.0 using setStoreValue and getStoreValue apis
