### ISSUE TITLE
Remove custom linter settings

### ISSUE THREAD

**Issue by felixblaschke** [rknell/alfred#17]
I understand that you are used to write strings with double quotes and like to explicit name types. On the other hand Dart is a language with a **convention over configuration** philosophy. Therefore I recommend using the default linter style that comes with **pedantic**.

The main advantage is easily readable and well maintainable code which leads to more acceptance to contribute and use Alfred.

You already acknowledge to enforce dartfmt code formatting in CI build. So we can go a step further and disable both custom rules in `analysis_options.yaml`.

Dart will automatically fix the code for you:
```
dart fix --apply
```

**Comment by rknell** [comment]
I hate double quotes and I find putting the type at the beginning of the variable to help me reason what I am about to, but I think you are right.

Im going to rip off the bandaid now and hopefully we don't have too many PRs coming down the pipeline. I checked the network graph and it looks like we are in the clear.
