### ISSUE TITLE
onNotFound handler is not functional

### ISSUE THREAD

**Issue by felixblaschke** [rknell/alfred#22]
While reviewing the routing algorithms I noticed a flaw which makes `onNotFound` handler not working as intended.

Alfred looks for any matching route. If he doesn't find any, it's a "not found" for him. This assumption is wrong because any middleware acts like an effective route. This results in using any middleware makes the `onNotFound` handler not functional.

Here is an example:
```dart
import 'package:alfred/alfred.dart';

Future<void> main() async {
  final app = Alfred(
    onNotFound: (req, res) => '404'
  );

  app.all('*', (req, res) { // mandatory middleware
    res.headers.set('X-Powered-By', 'Alfred');
  });

  app.get('/valid', (req, res) => 'Valid route');

  await app.listen();

  // GET 'http://localhost:3000/notvalid' => no 404
}
```

I tried to figure out the perfect moment for saying "not found". I realized the location where Alfred checks non-done request and prints out a warning is perfect for being "not found":
```dart
        /// If you got here and isDone is still false, you forgot to close
        /// the response, or your didn't return anything. Either way its an error,
        /// but instead of letting the whole server hang as most frameworks do,
        /// lets at least close the connection out
        ///
        if (!isDone) {
          if (request.response.contentLength == -1) {
            print(
                "Warning: Returning a response with no content. ${effectiveRoutes.map((e) => e.route).join(", ")}");
          }
          await request.response.close();
        }
```

**Comment by rknell** [comment]
If it hits that last function though it can be because the user neglected to return a response, not that a route was not hit.

Perhaps  404 would make sense if the req.route Param never gets set? It's late now and I need some sleep so might not be thinking clearly

**Comment by felixblaschke** [comment]
Yes. Sleeping is a good idea :)

Basically Alfred doesn't differ between **routes that act as middleware** and **routes that produce content**. Both a treated with the same routing algorithm. Both middleware and content-producer will set `_internal_route` / `req.route`.

There is a subroutine that processes all `middleware` directly attached to `HttpRoute`, which isn't a good pattern imo, cause it's something that behaves differently.

I can happen that a middleware sets relevant headers (like CORS which is `app.all('*', ...)`) but **no other route** adds some data. Such case wouldn't be handled by the notFound listener. But as a developer I would expect it.

**Comment by rknell** [comment]
So how about this logic -

If nothing is returned, and the route is a wildcard, then we also throw a 404?

If the route matches exactly, but the user fails to return any data, well thats on them and it throws a warning?

**Comment by felixblaschke** [comment]
> If nothing is returned, and the route is a wildcard, then we also throw a 404?

Agree. Usage case: A cors middleware modified headers but nothing else happens.

> If the route matches exactly, but the user fails to return any data, well thats on them and it throws a warning?

This might be a valid response. Usage case: `POST` to add a resource where a status ok (200) means "successful added resource"

Let's add the first rule (*If nothing is returned...*) and don't do warning on the second, then we try it out and look how it feels. Then we iterate on this topic again?

**Comment by felixblaschke** [comment]
Alternatively we do the warning thing on the second rule, unless a TypeHandler was involved. We add a `Status` typehandler where you can pass in a Dart io status code enum, i.e. 
```dart
app.post('resource', (req, res) => Status(HttpStatus.ok))
```

**Comment by rknell** [comment]
@felixblaschke do you feel this is handled now and can be closed?

**Comment by felixblaschke** [comment]
Yep.
