### ISSUE TITLE
Request/Response context

### ISSUE THREAD

**Issue by davidmartos96** [rknell/alfred#29]
It would be great to have a way of passing data around the middlewares or to the final endpoint. A use case could be an authentication middleware that obtains the user information so that it is available when you reach the GET/POST method.
For inspiration, here is how `shelf` handles it: https://pub.dev/documentation/shelf/latest/shelf/Request/context.html

Third party packages could use that to integrate with alfred (sessions, cookies, validation...)

**Comment by felixblaschke** [comment]
We already working on a solution for that: https://github.com/rknell/alfred/blob/master/lib/src/plugins/store_plugin.dart
It's not api final but you can already use it:

```dart

Future<void> main() async {
  final app = Alfred();

  app.all('*', (req, res) {
    req.setStoreValue('foo', Foo());
  });
  
  app.get('/path/to/url', (req, res) {
    Foo foo = req.getStoreValue('foo');
    foo.bar();
  });

  await app.listen();
}
```

**Comment by davidmartos96** [comment]
@felixblaschke Nice to hear! Feel free to close it then, or keep it open until that is merged :smile:

**Comment by rknell** [comment]
It's merged in and available on the prerelease version. If you are playing around Alfred make sure you jump on the preview versions, anything less than 0.1 is functionally stable, but there are a huge number of improvements in the pipeline, mostly thanks to Felix.

I've got a bunch of projects I want to use the changes in production with first before I bump it over so we can make any last minute adjustments before we lock anything in, but that will be finalised this week I would hope
