### ISSUE TITLE
How to use it in Flutter

### ISSUE THREAD

**Issue by pythonhubpy** [rknell/alfred#33]
A clear example is needed on How to use the package inside Flutter since it is mentioned that it can be used for Flutter.

**Comment by felixblaschke** [comment]
Hi, can you show me where Flutter support is mentioned?

**Comment by felixblaschke** [comment]
I'll guess you are referencing the auto-generated compatibility check on https://pub.dev/packages/alfred

The usage won't be any different when you use it in Flutter. Keep in mind that Flutter doesn't support all features on all platforms. For example Flutter web does not support the Dart IO api we use for alfred. Directory and File apis might not work on mobile platforms.

**Comment by rknell** [comment]
The directory and file APIs work just the same from my experience.

It would just drop in and work on every platform except web as @felixblaschke says - for practical purposes it probably doesn't make a lot is sense except in perhaps flutter desktop, but if you wanted to fire up a quick web server to share local app files, or a path the app has access to on Android you could do that.

In any case I'm not sure what you are looking for in an example @pythonhubpy - it works the same as in all the examples shown. Create an Alfred instance, add a route, and listen. Is there some specific use case you have tried and it didn't work?

**Comment by rknell** [comment]
Sorry a caveat with the directory side of things is you probably want to use the path package to find the right directory where files could be stored. That could be an example I suppose but at this point we might be hand holding a little too much - especially as it's showing more how to use a third party plugin than Alfred

**Comment by pythonhubpy** [comment]
**App.listen()** is however needed but how can I do that inside Flutter? Is there some way I could use it without app.listen()?

**Comment by rknell** [comment]
Resolved in https://github.com/rknell/alfred/issues/34
