### ISSUE TITLE
Replace http_server dependency (Bodyparser)

### ISSUE THREAD

**Issue by felixblaschke** [rknell/alfred#38]
Kevin Moo reported the discontinuity of the `http_server` package.
https://www.reddit.com/r/dartlang/comments/mkafju/palace_server_side_dart_framework/gtmmbp4?utm_source=share&utm_medium=web2x&context=3

https://pub.dev/packages/http_server

**Comment by felixblaschke** [comment]
@rknell 
I did a little bit of thinking about this. Do we really need 3rd party body parser with all it's features? What the main source of request body data? It's JSON. It's probably 99% json. Let's focus on this and focus on developer experience.

How do we expect developers to read the request body? This?
```dart
(req, res) async {
  var body = await req.body; // wtf is this body? no!
}
```

Most developer know exactly what is coming. A more convenient way to access request body is more like:
```dart
(req, res) async {
  var body = await req.asJson(); // i expect JSON
}
```

If really somebody implements content negotiation, he would check the `Content-type` header:
```dart
(req, res) async {
  if (await req.isJson()) {
    return myJsonHandler();
  }
  if (await req.isText()) {
    // ...
  }
}
```

If they really need to some exotic body parsing they can effortlessly delegate it to a 3rd party solution, because we are working on pure Dart io lib objects.

Any opinions?

**Comment by rknell** [comment]
Hey Felix,

Unfortunately yeah, while most data is JSON, I sometimes have to deal with multipart, url form encoded stuff, or just straight up file uploads. The http body parser was pretty awesome as it all just fed into the same json output. Im actually using the file uploads already in a project so can't ditch it now!

I was thinking as a future add on to add some extensions like "bodyAsMap", "bodyAsList" etc to easily extract it, but what was great was no matter what you threw at it it would just essentially spit out JSON.

I might have a dig through HTTP Server and see what it would take to extract the body parser. I can't imagine there would be much maintenance on that

**Comment by rknell** [comment]
I had a look at it, the code seems very clean and straightforward:
https://github.com/dart-archive/http_server/tree/master/lib/src

We would only need the HTTP body and "http_multipart_form_data.dart" files so I don't see an issue adopting it.

I've always felt a bit weird about needing to import the body parser in express separately. While I like things to be decoupled it irks me if there is a chance a core component wont keep up with the rest of the package - a part of the reason I'm not a fan of how disjointed shelf is - its one thing to be modular, but another thing to need to pull in a bunch of packages just to do the most basic stuff. I like to include the basics but make it extensible if you need some whacky extra feature.

With that said what are your thoughts about it? Separate package, internal, or roll our own. I'm leaning heavily against rolling our own - at the very least I would copy and paste 90% of the code to start with anyway and refactor from there.

**Comment by felixblaschke** [comment]
In my daily business we implement file upload as base64 encoded blobs inside json structures :D
If you say one's still need that features, I'm in to support that, too :-)

I quickly reviewed that package yesterday.
- For any type of body parsing it starts here: https://github.com/dart-archive/http_server/blob/master/lib/src/http_body.dart#L219 
- From this point it checks everything and parses every type.
- Also some tests are there https://github.com/dart-archive/http_server/tree/master/test

I also see a request body parser as something fundamental. Users shouldn't care about importing one for the most basic stuff.

I agree on copy pasting it to **internal** code. From this point we can (later) transform it to Alfred's needs. I also wouldn't restart reimplementing all that logic by my own. We definitely should use that as a base. HTTP protocol didn't changed.

**Comment by rknell** [comment]
Ok, i've pulled it into the main repo and removed the dependency.

Anyone with any advice about the licence would be appreciated though - it looks like BSD only applied to binary distributions so not sure how that affects the code here. Very happy to leave a reference to the google authors, but also wouldn't want to implicate them in any future changes we make.

Closing but welcome future comments.

**Comment by felixblaschke** [comment]
From https://github.com/dart-archive/http_server/blob/master/LICENSE I understood, that we should add all content from their LICENSE file to all dart files to be compatible. Or?

And in our LICENSE file we should note that parts are BSD licensed?

**Comment by rknell** [comment]
I have added a note and put the BSD licence in there. In the http_server parts we bought over they have that comment in the header which I have left and feel fulfils the requirement.
