### ISSUE TITLE
Cannot install as dependecy

### ISSUE THREAD

**Issue by julianoventola** [rknell/alfred#43]
I tried to start a new project in dart to test it, but i keep getting the message: A package may not list itself as a dependency
![image](https://user-images.githubusercontent.com/28475558/114945633-15fd5c80-9e20-11eb-92e0-dafd04cbc43e.png)

**Comment by rknell** [comment]
Hey @julianoventola 

It looks like you named your project alfred (up the top) try changing the name of your project to something like `alfred_test` and have another go.

**Comment by julianoventola** [comment]
@rknell I have no words to describe my shame... thank you very much!
Also, greaaat job! 😁

**Comment by rknell** [comment]
Haha don't worry - I probably do something like that at least once a day
