### ISSUE TITLE
Stream - clarificatoin

### ISSUE THREAD

**Issue by subzero911** [rknell/alfred#45]
You wrote in docs:
![image](https://user-images.githubusercontent.com/12999702/115677758-7da03400-a359-11eb-8d6c-2661fb4de641.png)

What did you mean?

**Comment by felixblaschke** [comment]
I think you have a rendering issue in your browser. For me it looks like:

<img width="863" alt="shot" src="https://user-images.githubusercontent.com/26407468/115692205-0f5e7000-a35f-11eb-9753-b508d8889e78.png">

It's a `Stream<List<int>>` representing a binary stream.

**Comment by rknell** [comment]
Fixed the docs so the types aren't randomly stripped off
