### ISSUE TITLE
websockets

### ISSUE THREAD

**Issue by subzero911** [rknell/alfred#46]
Thanks for your work. I really enjoy your package.
How about adding an ability to create a websocket server?
See GetServer https://pub.dev/packages/get_server :

![image](https://user-images.githubusercontent.com/12999702/115678160-e4255200-a359-11eb-9c3f-6de613c80354.png)

**Comment by felixblaschke** [comment]
You mean this? :-)
https://github.com/rknell/alfred/tree/master/example/example_websocket

**Comment by subzero911** [comment]
Yes! Cool, I didn't know you've already implemented it.

**Comment by subzero911** [comment]
I believe you should mention it in docs.

**Comment by rknell** [comment]
Agree! I thought it was in there.

I'm going to give the docs another once over - a lot has changed since the initial write up so would be good to do a refresh

**Comment by rknell** [comment]
Added!
