### ISSUE TITLE
Community suggestions: deployment?

### ISSUE THREAD

**Issue by rknell** [rknell/alfred#47]
Hi All!

My current deployment strategy is to use Aqueducts heroku buildpacks or to use a docker compose script to fire up a dart VM and build a Linux binary, then upload that to my server and use PM2 to keep it running. I put nginx in front of it to manage SSL certs.

There has to be a better way!

In any case I want to document a deployment flow as I feel it's the missing piece.

Any community suggestions about what you do?

**Comment by rknell** [comment]
Well the answer to this seems to have come in the form of the Dart 2.13 announcement. I have added a deployment tutorial to the readme with a docker container running on Google Cloud Run

**Comment by ramyak-mehra** [comment]
Running the server on google cloud run would eliminate the need for using isolates? also, how would be managing the database connections? I have not tried the google cloud run personally.

**Comment by rknell** [comment]
Yeah it would remove the need for isolates - its a single core setup. I have only tried it in trivial projects so far, my go to solution for my big projects at the moment is a VPS using NGINX and keeping it alive via PM2. New projects I will be pusing a cloud run solution.

I don't think it should be an issue for DB connections unless it spins up LOTS of servers, and each instance of cloud run will handle 200 simultaneous connections by default, so it will pool them and you would need a lot of traffic to flood a server like postgres or mongo
