### ISSUE TITLE
Authentication support

### ISSUE THREAD

**Issue by AKushWarrior** [rknell/alfred#48]
Hey, I figured I'd open a tracking ticket, since I like the way this project is progressing. Most server-side frameworks have ways (built-in or third party) to authenticate users; do you think that's something you'd be interested in building out down the line? 

Obviously, there's a cost in terms of complexity and ease of maintenance; on the other hand, authentication is probably the most universal of the currently unmet needs in terms of the Dart server ecosystem.

**Comment by rknell** [comment]
I am interested in authentication support but would be hesitant to be too prescriptive about it - in that it might be a good chance to be a plugin that extends the core framework. Or what I would ideally like to see is another package that provides authentication support and an api that anyone can use, something the community can take forward with any web framework and even maybe roll it into a Flutter app. Then that package would either give a guide to integrate with Alfred, and/or I would have an authentication section that outlines how to plug it in (ideally in about a line or two of code)

The other issue I have with it is I tend to just either roll my own authentication (generate and validate JWTs these days) and chuck a middleware on any route that says "isAuthenticated" and bumps the user if the auth fails. I have looked at passport multiple times in the past but couldn't really work out what benefit it provided me. I know this is probably a blind spot in my experience as a dev, but what would you consider to be the core features of an authentication framework? ie what would I even be producing?

**Comment by AKushWarrior** [comment]
Given the similarity of Alfred to Express, let's roll with passport as the example of choice. While it's easy enough to roll your own token-based auth, scaling it is annoying, and with each incremental change in complexity cascades across the application. Most mature services want some OAuth integration (notably Google and Facebook, but also GitHub and Twitter and a ton of other ones).

As I understand it, an auth library takes away all of the complexity and hides it behind a clean API, with a one liner that can be used to configure and authenticate the entire application. Obviously, you can roll it yourself, but that's true of pretty much everything in a server-side ecosystem. It's just a quality-of-life feature.

**Comment by rknell** [comment]
Ok, so I have had a chance to go back and look at some examples using PassportJS - and to my mind its still just way to complex. The homepage has a promise of a simple one liner but when you dig a little deeper its much more complicated than that even just for basic authentication.

What I would like to see is something like this pseudo code: 

```dart
final basicAuth = BasicAuthHandler(validator: (username, password){
    // Go to the database and get your username and password
})

app.get('/authenticatedrequest',(req,res)=>'youre in', middleware: [basicAuth]);
```

The problem though comes down to its just not my area of expertise to design an API that is flexible enough but also so simple its a pleasure to work with. If there is someone in the community who has designed these sorts of things before I would be very happy to work with them. One of the great things about Alfred is its just passing through the dart:io HttpRequest and HttpResponse classes, so a system that works on the back of dart:io should drop in work with Alfred.

What I will do in the meantime is explore a few options and write up some tutorials to give some guidance. I will also look into integrating session management, as I think that should be bundled as a core part of the library - with a default to the local file system for persistence, but the ability to use a redis store or some other database if you choose to.

**So leaving this open for now as a placeholder for my work above, but also for community suggestions about an api that is elegant and flexible.**

**Comment by AKushWarrior** [comment]
@rknell Yeah, so the base of authentication would likely have to be session management. I think that's a fairly clean feature to implement from a maintenance perspective; you just leave most of the details (i.e. how are sessions stored/retrieved, the schema of a session) to the consumer of this package via a callback interface, and perhaps handle session IDs by inserting a unique id into each request (again generated by a consumer-provided callback).

Then, the authentication thing would be pretty easy to code. Again, the consumer provides redirects/callbacks to handle each non-success case (failure, maybe uncreated account?), and we just inject the authenticated session information into the success case callback (which would be `(req,res)=>'you're in'` in your example`, I believe that you can do that using extension methods). 

There is more complexity introduced by things like OAuth, tiered session levels, or whatever. Those can be built out by third-party packages down the line.

**Comment by ramyak-mehra** [comment]
I have been building a basc authentication service for my project. There is a little bit of stuff It needs to support but it could be a starting point if anyone's trying.
https://github.com/ramyak-mehra/LinkZ/tree/master/packages%2Fauthentication

I am open to any recommendations around the same 🙂

**Comment by rohitsangwan01** [comment]
@rknell , your authntications sevices seems good , is it usable in production ready , or can you port that as an alfred extension on pub.dev

**Comment by rknell** [comment]
Anyone coming here should check this example:

https://github.com/rknell/alfred/issues/88
