### ISSUE TITLE
== instead of =

### ISSUE THREAD

**Issue by modulovalue** [rknell/alfred#49]
This looks like a bug

https://github.com/rknell/alfred/blob/13b0c1b8bca22ffc0ddac76d3e5d8804c38bce88/lib/src/extensions/response_helpers.dart#L34

**Comment by modulovalue** [comment]
a pdf mime detection test fails if this is turned into an assignment. So I guess that case can be removed?

**Comment by rknell** [comment]
Good point! Working on it

**Comment by rknell** [comment]
Resolved in 0.1.4+5

**Comment by rknell** [comment]
hey @modulovalue  - I just checked the network from the forks and noticed you are doing a lot of private work on this project, If you want to submit some PRs with any improvements you make that would be great!

**Comment by modulovalue** [comment]
I'm experimenting with making alfred more type safe. Almost all apis have changed so It would be a little hard to make a PR without breaking everybody.
