### ISSUE TITLE
[proposal] tutorial, community (discord? slack?) and contribution guide

### ISSUE THREAD

**Issue by iapicca** [rknell/alfred#5]
I love to see such a project come to life!
it would be great if there was:

- a tutorial or in dept documentation from a deployment from the scratch
- a community where to get help, possibly `discord` or maybe `slack`
- a contribution guide

thanks for the attention

**Comment by rknell** [comment]
Hey @iapicca thanks for the feedback!

I definitely want to do a couple of in depth tutorials. I'm a big believer in making things as easy as possible to drive adoption.

A contribution guide will pop up in the next couple of days on the readme. I already have travis in place and it will reject on some pretty strict formatting and linting rules, but I want this to be a community project so thats a no brainer.

Which leaves me with the middle point - the only issue I have with a discord or slack server is that I might not be super active on it, and there is nothing worse than looking for help and it being missed. Personally I would prefer a subreddit as that is where I spend most of my time, but I think for the next little while I might just recommend opening an issue until the project reaches a critical mass.

Not saying no - just saying I don't want to promise something I may not deliver. I'll add a where to get help section on the readme too when I go and add the contribution guidelines.

**Comment by iapicca** [comment]
@rknell 
I just took the liberty 
https://medium.com/@iapicca/alfred-an-express-like-server-framework-written-in-dart-1661e8963db9

if you want me to fix anything just say the word

**Comment by rknell** [comment]
Thanks so much for this! Its great!

I'm really overwhelmed with the support this little project is getting

**Comment by rknell** [comment]
Thanks @iapicca - I've added a link to your quickstart guide on the main page and added a quick contribution guide
