### ISSUE TITLE
How to stop server by key or just by stop button from VSCode?

### ISSUE THREAD

**Issue by alexandrim0** [rknell/alfred#51]
It is not clear to me how to stop server.
I use VSCode and have find pid to kill server process.
It inconvenient for many reasons!

Would be nice to see any advise!
Thanks!

**Comment by rknell** [comment]
Hey @alexandrim0 

I guess it depends on how you start it. If you just kick it off with `dart server.dart` from the command line then you can just push ctrl-c to close it down

If however you are daemonising it (for example starting it with `dart server.dart &`) then you would need to kill the process by finding the PID and closing it that way. Alternatively you could write an endpoint that calls `exit(0);` that shuts it down.

Personally I just use the ctrl-c method / Android studio's run command to start and stop it, I don't use VSCode, but there isn't any reason it should keep the dart process running.

In production I use PM2 to keep it alive, or heroku or google cloud run.

How are you starting it?

**Comment by alexandrim0** [comment]
Ok, while developing it I will just start it from command line, not from VSCode by hotkey.
It works for me.
Thank you!

**Comment by rknell** [comment]
So I had a little dig, but as I said I don't use VSCode so i'm not at all an expert.

I was able to get it to run multiple times using F5 command using this launch config:
```javascript
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Dart",
            "type": "dart",
            "request": "launch",
            "program": "app.dart"
        },
    ]
}
```

The trick though was to "Stop" it (Shift F5) before starting a new one. When I stopped it I had no problem starting it again.

My server was very simple though, this was the code:

```dart
import 'package:alfred/alfred.dart';

main() async {
  final app = Alfred();

  app.get('/test', (req, res)=>{"result":  true});

  await app.listen();
}
```

**Comment by alexandrim0** [comment]
Yes, it stops if was running by F5.
But if program started by Ctrl-F5 it wont stop.
So, it is not a problem of Alfred.
Thank you!
