### ISSUE TITLE
Using socketIO

### ISSUE THREAD

**Issue by Donk3ys** [rknell/alfred#52]
Ive been trying to integrate the [socket_io package](https://pub.dev/packages/socket_io) with alfred but socket_io seems to only allow StreamServers not HttpServer.

Has anyone found a way to integrate both?

**Comment by rknell** [comment]
Hey Donk3ys,

The current strategy is what is proposed in the example file. Will that work for you?

**Comment by Donk3ys** [comment]
Thanks for the reply. 

The example file works fine for "vanilla websockets" but im working on a project where I need to implement socketIO. 

I think its more an issue with the [socket_io](https://pub.dev/packages/socket_io) package and not Alfred, but was hoping someone could lead me in the right direction for integrating both.

By the way, thanks for creating this package im enjoying playing around with it and hope to use it for production soon

**Comment by rknell** [comment]
Ahh I understand. Yeah sorry I haven't had any experience trying to use socketio with Alfred yet (or a dart backend for that matter!) only used it with node so can't comment on it.

If you do work it out I would be very grateful if you report back what you found
