### ISSUE TITLE
How to stop server programmatically?

### ISSUE THREAD

**Issue by farukaziz** [rknell/alfred#57]
I really like this package and appreciate your work.  
In my application I need to stop the server on a button press but I did not find any helper method to stop the running server.

-  How to check the server is running or not?
-  How to stop the server if already it running?

```dart
import 'package:alfred/alfred.dart';

void main() async {
  final app = Alfred();
  app.get('/example', (req, res) => 'Hello world');

  await app.listen();

 // something like below
 // app.isRuuning();
 // app.stop();
}
```

**Comment by rknell** [comment]
Hey @farukaziz 

Just call await app.close();
```dart
import 'package:alfred/alfred.dart';

main() async {
  final app = Alfred();

  await app.listen();

  await app.close();
}
```
