### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by FaisalAbid** [rknell/alfred#58]
Is this production ready?

**Comment by rknell** [comment]
Hi @FaisalAbid,

I consider it production ready. The underlying framework its built on is very mature and built into dart (dart:io), the api is stable and I have personally used it in some fairly demanding applications without a hiccup.

The main thing with the code is I have tried to make it accessible - so if there is anything you need to modify, with little effort you should be able to find what you need to and make a change. So even if you had to pick it up and run with it, it would be much the same as if you just built a framework on top of dart:io yourself.

The other thing to note is that it exposes the dart:io classes directly to you, so if there is anything tricky that hasn't been thought about it should be trivial to do without needing to make adjustments directly to Alfred.
