### ISSUE TITLE
RouteMatcher & current RegExp

### ISSUE THREAD

**Issue by d-markey** [rknell/alfred#60]
Route matching is based on regular expressions that are currently built by the `RouteMatcher` class each time Alfred receives a request. The current implementation also eagerly evaluates all routes even if the first route will do.

I proposed a change to build the `RegExp` when the route is created and avoid creating the same `RegExp` over and over again. I also turned the `match()` method into a generator to avoid systematic evaluation of all routes.

I also considered changing the way routes ending with a `*` segment works but this would be a breaking change. Currently, if the last segment is a `*`, the `RegExp` is terminated with:

```
        /// Generously match path if last segment is wildcard (*)
        /// Example: 'some/path/*' => should match 'some/path'
        matcher += '/?.*';
``` 

How would you consider the following change? The idea is to match `some/path`, `some/path/`, `some/path/whatever`, but not `some/pathbreaking`.

```
        /// Generously match path if last segment is wildcard (*)
        /// Example: 'some/path/*' => should match 'some/path' but not 'some/pathology'
        matcher += '(?:/.*|)';
``` 

I also considered using named groups in the `RegExp` and capture parameters at match time to avoid additional parsing done in `getParams()`, but I'm not sure how it would play with `NotMatchingRouteException`. This would certainly be a breaking change too, although I believe the current implementation is broken because it expects the input Uri to contain as many segment as the route does. This will not work with wildcards eg.

- route `/some/*/thing/:id` should match Uri `/some/path/to/thing/abc`  but `getParams()` will throw (4 segments vs. 5)
- route `/some/thing/:id/*` should match Uri `/some/thing/abc`  but `getParams()` will throw (4 segments vs. 3)

Leveraging named groups would correctly capture parameters for such routes and `getParams()` could be removed altogether. If the route matches, there should be no reason why `getParams()` throws.

**Comment by rknell** [comment]
Hey David,

Thanks for all your input. I've got to go through it, but if it's broken like in the example you give I can see us pushing out a breaking change, otherwise the no. 1 rule us pretty much keep the api as is. I have had a quick look at the pull requests and so far I'm pretty happy with all the proposed changes, just need some time to really read them and test them out before merging them in.

**Comment by d-markey** [comment]
Hello Ryan,
    
Thanks for your feedback :-) let me know if I can help with the params part or with my pull request.

-------- Message d'origine --------
De : Ryan Knell ***@***.***> 
Date : 09/08/2021  00:55  (GMT+01:00) 
À : rknell/alfred ***@***.***> 
Cc : David MARKEY ***@***.***>, Author ***@***.***> 
Objet : Re: [rknell/alfred] RouteMatcher &amp; current RegExp (#60) 


Hey David,
Thanks for all your input. I've got to go through it, but if it's broken like in the example you give I can see us pushing out a breaking change, otherwise the no. 1 rule us pretty much keep the api as is. I have had a quick look at the pull requests and so far I'm pretty happy with all the proposed changes, just need some time to really read them and test them out before merging them in.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/rknell/alfred/issues/60#issuecomment-894867677",
"url": "https://github.com/rknell/alfred/issues/60#issuecomment-894867677",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by d-markey** [comment]
Hello again,

FYI I have setup a test for routes mixing parameters and wildcards to demonstrate the problem above.

See test report from https://github.com/d-markey/alfred/runs/3365620031?check_suite_focus=true (lines 477+, test name "it handles params in routes with wildcards"). The route matches all right, but when the uri introduces additional segments compared to the route, the route handler fails when user code tries to get the parameter value.

**Comment by rknell** [comment]
Thanks David,

Yeah that makes it clear what you are trying to achieve. If you can come up with a solution that gets that test to pass and doesn't break the others happy to accept it. Its Friday afternoon and I am cooked right now, so not thinking the solution through in its entirety, but you did a great job on the other PR.

**Comment by rknell** [comment]
Also I'm not really considering it a breaking change as its a routing strategy that wasn't considered initially. I will communicate it as something to look out for, but I don't think it should affect anyone adversely.

**Comment by d-markey** [comment]
Hello Ryan,

I've pushed some changes to better handle parameters.
I've also added the possibility to validate parameters and provide some kind of typing as well.

Best regards and thanks for your comments :-)

**Comment by d-markey** [comment]
Hello Ryan,

I've reworked the parameter validation bits and took inspiration from your type handlers mechanism. I found my first try was way too hardcoded and not flexible enough. I believe my pull request should now be acceptable. Tests have been updated and new tests added as well.
