### ISSUE TITLE
SSL (https) support

### ISSUE THREAD

**Issue by boganiLuca** [rknell/alfred#63]
I was looking for a server framework for my flutter web app, and after some research I stumbled upon Alfred, which, I must say, fits perfectly my needs in term of simplicity and independence.
Since I need to have SSL support, I looked around in docs and issues, found nothing, so I started right away to add the functionality myself by extending Alfred and writing a `secureListen` method that would mimic the original `listen` but that would use Http.bindSecure instead. But then I noticed that there's the `_incomingRequest` method that's not visible from my custom Alfred, that in turn uses other private methods.
Do you know any simple way to make this work?

**Comment by rknell** [comment]
Gong to close this for now as there is nothing that will be directly actioned as a result. If anyone wants to raise it further happy to reopen
