### ISSUE TITLE
What is alfred-way of returning response in this code?

### ISSUE THREAD

**Issue by bubnenkoff** [rknell/alfred#64]
I have got follow code:
```
  app.post('/sql-insert', (req, res) async {
    print("sql-insert handler");
    final body = await req.body; //JSON body
    try {
      var insertResult = await db.sqlInsert(body as Map<String, dynamic>).timeout(Duration(seconds: 140));

      switch (insertResult) {
        case dbEnums.success:
          return res.json({'status': 'success'});
        case dbEnums.insertFailed:
          return res.json({'status': 'failed'});
        default:
          return res.json({'status': 'unkownStatus'});
      }
    } on TimeoutException catch (e) {
      print("Too long request: ${e.message}");
      print("Too long request duration: ${e}");
    } catch (e) {
      print("[ERROR] sql-insert exception: $e");
    }
  });
 ```
 
This was correct in old http framework, but it seems that in alfred instead of:
`return res.json({'status': 'failed'});`
I should write:
`await res.json({'status': 'failed'});`

Because with my code I am getting error:
```
2021-09-12 12:04:11.206949 - error - No type handler found for _HttpResponse / Instance of '_HttpResponse'
```

Could you show me right version of how code should look like?

**Comment by d-markey** [comment]
You should `return {'status': 'failed'};` really.

When Alfred receives a response from your request handler (`return something;`), it will try to find a TypeHandler matching the actual type of `something`. Alfred provides several type handlers out of the box, including one for `Map<String, dynamic>` which would be the type of your JSON object.

Note that if you return `null`, Alfred will try to find another route matching the incoming request and eventually raise a 404 if no other route will do.

When you `return res.json({'status': 'failed'});`, Alfred receives an _HttpResponse object and there's no type handler for HttpResponse, hence the log message.

**Comment by bubnenkoff** [comment]
Thanks!

**Comment by d-markey** [comment]
For most use cases, I believe you won't be needing `res.json()` anymore :) simply return the object.
You just have to make sure your object is serializable through `jsonEncode()`.
