### ISSUE TITLE
Question about CORS

### ISSUE THREAD

**Issue by bubnenkoff** [rknell/alfred#65]
In my last framework the was string that allowed me all connections:
```
app.use(CorsMiddleware.use(origin: '*', allowedHeaders: ['Content-Type']));
```
In alfred I tried next string:
```
  app.all('*', cors());
```
and:
```
app.all('*', cors(origin: '*'));
```
But after starting Flutter project in Chrome I am getting error:
```
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

What I am doing wrong?

**Comment by d-markey** [comment]
Hello,

where did you install the `cors` middleware?
For the `cors` middleware to run before any request is served, it must be installed right after instantiating Alfred:

```
   final app = Alfred();
   app.all('*', cors());
   // install your app routes after cors
```

Routes will be processed in the order they were registered so if any route is installed before `cors`, and the rout returns a value, the cors middleware will not run.

**Comment by d-markey** [comment]
In fact the cors middleware is a route like any other, except that it returns `null` so Alfred will continue looking for a route from your app after running cors.

**Comment by rknell** [comment]
thanks @d-markey! That is correct

**Comment by bubnenkoff** [comment]
Thanks for explanation! Moving 
```
app.all('*', cors(origin: '*', headers: '*'));
```
direct after 
```
final app = Alfred();
```
solved my problem!
