### ISSUE TITLE
When Multi threading and isolates can be helpful? 

### ISSUE THREAD

**Issue by bubnenkoff** [rknell/alfred#67]
Hi! Could you explain me the situation when multi threading and isolates can be helpful?

My app have two handlers:
/count 
/sql-upsert
/statistic

I have 4 instance of ParserApp. Every instance after run:
1. Send count request (DB is very big so it may take up to 10 seconds for every request)
2. Start processing files and 
2.1 sending to `sql-upsert` result of parsing as SQL plain text statement, 
2.2 update status of processed files

/statistic handler is for big and complex request that run can take up to 30 minutes. 

So could the single isolate (that used by default) be bottleneck in my case? And could isolates  be helpful? 

It just seems to me that all IO falls on the database or am I wrong?

upd:
Could be PostgreSQL connection object is bottleneck? If I am using it from handler above? I am using this driver: https://pub.dev/packages/postgres

**Comment by rknell** [comment]
Its possible you could cause a bottleneck anywhere and this is really more of a dart problem than an Alfred one. The one bit of advice I can give you is that Alfred will only keep a certain number of connections "processing" at one time (this is configurable), the rest are queued up so you don't crash your server. 

From Alfred's standpoint you need to respond with something like a 202 response code (Processing), then do what you need to do from there. You might want to do that work on its own isolate and keep Alfred in single isolate mode. But the long and short of it is just make sure you return a response at the earliest possible time.

**Comment by d-markey** [comment]
IMO adding new Isolates will not improve your DB/query performance. New threads/Isolates would make sense when processing is CPU intensive, to avoid blocking the event loop. But DB queries are essentially IO-bound so I expect the event loop spends most of its time doing nothing but awaiting results from DB or new incoming requests.

**Comment by bubnenkoff** [comment]
@d-markey @rknell hey! Could you look at this question please https://stackoverflow.com/questions/69552893/wrong-order-of-execution-async-handler

Maybe it's case for isolates?

**Comment by bubnenkoff** [comment]
@d-markey
Should I do `await` here?
`await File('result.json').writeAsString(prettyJson(data.toString()));`
or I could write to file without it? And it will be written sometimes late? dumps are optional for me

**Comment by d-markey** [comment]
IMO Timer.Periodical is nonsense because it doesnt return the data to you code, it merely writes it to a file. So while loop makes more sense. However you probably want to try/catch individual calls to `await http.get()` to ensure the while will actually loop. In your code, when `http.get()` raises an exception, the catch block will terminate the loop and you will see no retry.
