### ISSUE TITLE
What is alfred way to convert object to Map?

### ISSUE THREAD

**Issue by bubnenkoff** [rknell/alfred#68]
I am not sure if there is any best-practice about how to use handlers, but mine is look next:

```
  app.post('/count', (req, res) async {
    print('count handler');
    final body = await req.body; //JSON body
    try {
      var r = await db.getCountForProcessing(body as Map<String, dynamic>).timeout(Duration(minutes: 2));
      await res.json({'status': 'success', 'data': r}); // yes I will replace it to return later
    } catch (e) {
      print('[ERROR] count handler: $e');
    }
  });
  ```
```
  Future<dynamic> getCountForProcessing(Map body) async {
    try {
      List<List<dynamic>> result = await connection.query(body['sql']).timeout(Duration(minutes: 5));
      if (result.isNotEmpty) {
        print('COUNT for processing: ${result[0][0]}');
        return result[0][0];
      } else {
        print('COUNT: No files for processing'); 
        return [];
      }
    } on PostgreSQLException catch (e) {
      print(e);
    }
  }
 ```
 
The problem that `body` in alfred have type `Object?`, but my handler expect: `Map body`. As temporal solution I used: `body as Map<String, dynamic>` but don't sure if if correct, and maybe I should change functions to accept `Object?` instead of `Map` ?

**Comment by rknell** [comment]
I'm not sure I understand. If you are writing your own handler, look at the typehandler examples for JSON. However if you are just returning a Map<String, dynamic> it should just work and handle it correctly.

https://github.com/rknell/alfred/blob/master/lib/src/type_handlers/json_type_handlers.dart

Note these bits which detect the type and deal with it:
```dart
TypeHandler get jsonMapTypeHandler =>
    TypeHandler<Map<String, dynamic>>(_jsonHandler);

TypeHandler get jsonListTypeHandler => TypeHandler<List<dynamic>>(_jsonHandler);
```

**Comment by d-markey** [comment]
Alfred also defines an extension getter on HttpRequest : `bodyAsJsonMap`.

So `var r = await db.getCountForProcessing(body as Map<String, dynamic>).timeout(Duration(minutes: 2));` can be rewtitten as `var r = await db.getCountForProcessing(bodyAsJsonMap).timeout(Duration(minutes: 2));` and your `getCountForProcessing()` function will receive a `Map<String, dynamic>` object.

**Comment by bubnenkoff** [comment]
@rknell I tried to asked about what type is preferred to accept in function `Object?` or `Map<String, dynamic>`? Of function accept `Map<String, dynamic>` I need to cast `Object?` to it.

@d-markey yes, thanks! Important mention.

**Comment by bubnenkoff** [comment]
@d-markey 

But why example from docs is:
```
  app.post('/post-route', (req, res) async {
    final body = await req.body; //JSON body
    body != null; //true
  });
  ```
but not:
```
  final body = await req.body as Map; //JSON body
```
