### ISSUE TITLE
Support for all HTTP verbs

### ISSUE THREAD

**Issue by felixblaschke** [rknell/alfred#7]
Currently Alfred only support a few HTTP methods:
```dart
enum RequestMethod { get, post, put, delete }
```

Some are missing, especially PATCH (used in REST) and OPTIONS (for CORS implementation)

Reference: https://developer.mozilla.org/de/docs/Web/HTTP/Methods

**Comment by rknell** [comment]
Created the extra types and added a CORS module.

Available in 0.1.0
