### ISSUE TITLE
FormatException: Missing extension byte

### ISSUE THREAD

**Issue by bubnenkoff** [rknell/alfred#71]
I am getting error on receiving JSON with curl.
```
curl -X POST http://127.0.0.1:3000/ctr \
   -H 'Content-Type: application/json' \
   -d '{"selected_region": ["Республика Адыгея"]}'
```
it's seems that it can't decode Cyrillic.

error:
```
2021-10-12 22:39:28.528959 - info - POST - /ctr
2021-10-12 22:39:28.541953 - error - FormatException: Missing extension byte (at offset 23)
2021-10-12 22:39:28.542922 - error - #0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1892:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1620:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#9      _HandleErrorStream._handleData (dart:async/stream_pipe.dart:253:10)
#10     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1620:10)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#13     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#14     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:119:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:188:5)
```

app code:
```
// ....
  final app = Alfred();
  app.post('/ctr', (req, res) async { // complex tender request
    var data = await req.body;
    print('data: $data');
    await res.json({'data': 'ok'});
  }); 

  await app.listen();
```

**Comment by rknell** [comment]
Ok @bubnenkoff I have had a further look and wasn't able to reproduce the issue locally.

I have added a new test like so:

```dart
   test('it handles cyrillic bodies', () async {
    app.post('/ctr', (req, res) async {
      // complex tender request
      var data = await req.body;
      // print(req.contentType); //application/json; charset=utf-8
      // print('data: $data'); //data: {selected_region: [Республика Адыгея]}
      // print(data.runtimeType); //_InternalLinkedHashMap<String, dynamic>
      await res.json({'data': 'ok'});
    });

    await http.post(Uri.parse('http://localhost:$port/ctr'),
        body: '{"selected_region": ["Республика Адыгея"]}',
        headers: {'Content-Type': 'application/json'});
  });
```

And it completes as expected with no errors. I also ran the same test against postman, this time making sure the urf-8 encoding wasn't added automatically to the header - also worked.

Then I went and ran your cURL example against it and it also worked, returning:
<img width="515" alt="Screen Shot 2021-10-13 at 9 12 36 am" src="https://user-images.githubusercontent.com/5875053/137041179-4a7a0e41-1d86-4cad-94e1-b898d5b61984.png">

The good news is it seems Alfred does handle cyrillic characters and we now have a test for it, the bad news is I will need more information / its something else thats going on.

Maybe try it against master and see if its something that has come down the pipeline that is getting it over the line?

Going to close for now, but feel free to reopen if you are still having issues.

**Comment by bubnenkoff** [comment]
@rknell I rechecked it again. It's strange it's seems that curl do wrong cyrillic encoding, because sending JSON from other tool work fine. 
Thanks for checking!

**Comment by d-markey** [comment]
From what shell are you running curl? If you're using Windows/DOS, I suppose the encoding used by the terminal would be something like windows-1251 and I'm not sure CURL will encode the payload as UTF-8 (`application/json` is UTF-8 by default). Maybe try with `-H 'Content-Type: application/json; charset=windows-1251'`. Or check the bytes of the payload received by Alfred to find out which encoding was used.
