### ISSUE TITLE
Empty JSON body throws an error

### ISSUE THREAD

**Issue by tomassasovsky** [rknell/alfred#73]
For testing purposes, I sent a request from postman and made the body a JSON, but with a string containing nothing but a space.
This error was thrown when trying to read the body:
![image](https://user-images.githubusercontent.com/63405252/143605695-301ce4ff-3f4e-4fc9-9dcb-7e2abaf5ffe1.png)

Maybe a validation could be used to check if the jsonDecode throws an error, and if so return a 400 bad request?

**Comment by rknell** [comment]
Hmm,

I see you point but I also want to be careful not to swallow too many errors blindly for the user - sure in this case it was a space, but if you had some other dodgy json (such as a trailing comma) and that fails validation then I want the server admin to be able to easily see what happened. That was one of my frustrations with Aqueduct - the errors were incomprehensible.

However, it should definitely not kill the server, and should throw a 400 error back to the user.

So I wrote this test just now to test it and it appears to already be doing that correctly:
```dart
  test('it handles invalid json input', () async {
    app.post('/test', (req, res) async {
      await req.body;
    });
    final response = await http.post(Uri.parse('http://localhost:$port/test'),
        body: ' ', headers: {'Content-Type': 'application/json'});
    expect(response.statusCode, 400);
  });
```

Is there something else you were doing that was taking the server out?

**Comment by tomassasovsky** [comment]
also got this when calling await req.bodyAsJsonMap:
![image](https://user-images.githubusercontent.com/63405252/143664632-509cf2ad-63fa-4a83-8b28-7b5da03f9ef7.png)
