### ISSUE TITLE
cookies support

### ISSUE THREAD

**Issue by bubnenkoff** [rknell/alfred#75]
I would like to create simple site with authorization. So it's seems the only way to keep users login between browser restart (correct me if not) to have cookies support.  Is it possible with Alfred?

**Comment by d-markey** [comment]
Hello @bubnenkoff, of course it's possible.
Create the cookie you want upon successful authentication and send it to the user via HttpResponse (https://api.dart.dev/stable/2.14.4/dart-io/HttpResponse/cookies.html). When the user navigates, the user's browser will send it back and you will be able to inspect its content in your app via HttpRequest (https://api.dart.dev/stable/2.14.4/dart-io/HttpRequest/cookies.html). Also make sure your cookies are well secured if they carry authentication data (HTTPS, HttpOnly, expires...).

**Comment by rknell** [comment]
Closing this one because using the dart io methods is the right advice
