### ISSUE TITLE
API Versioning

### ISSUE THREAD

**Issue by tomassasovsky** [rknell/alfred#76]
Hi Ryan,

I was wondering if this package supports some kind of versioning for an API, so you can release specific apps that work with specific versions (and nothing gets broken on a new release).

**Comment by rknell** [comment]
It supports it in so much as it doesn't prevent it, but there is no specific built in function to do it.

In my mind there are a couple of ways I would architect it - first you could maintain a list of routes with something like

/api/2022-01/.....

You can copy / paste that to make a whole new set of routes. This feels like it will become unmaintainable pretty quickly.

Alternatively, and similar to something I have done in the past, I would create a "Route" class which handles registering the routes and you add them to a list and iterate over them, calling a "register" function on each class, but essentially its doing the same thing you did above, just keeping it in a box.

However to really and truly maintain different versions i would probably:

1. Run each version of the api on a different git branch
2. Deploy each version to a VPS on a different port ie 3000, 3001, 3002 etc and use NGINX to handle the routing. Alternatively use google cloud run to host a different version of each app at a new endpoint, and maybe make a CNAME subdomain which points to the google cloud run version with something that makes sense, ie `api-2020-01.yourdomain.com`.
3. Make sure you create a "deploy" script which handles deploying to the right place. However in my experience this gets messy and there is probably a better way, maybe even read the name of the git branch and make changes from there, not keeping it under version control, or running it as a different repo. You just don't want to accidentally overwrite an old API version with a new one.
