### ISSUE TITLE
Request for a simple frontend example to upload file

### ISSUE THREAD

**Issue by kalmigs** [rknell/alfred#77]
Hi,

As said in the title, can someone provide an example that will work on the backend example here: https://github.com/rknell/alfred#file-uploads.

Thanks!

**Comment by d-markey** [comment]
Hello, the example code was flawed, I just fixed it.

To implement a simple frontend, you can add this handler (shameless copy/paste from [Issue #80](https://github.com/rknell/alfred/issues/80) by @paulscliu):

```
app.get('/html', (req, res) {
    res.headers.contentType = ContentType.html;
    return '''<html>
          <head>
            <title>Image Upload Server</title>
          </head>
          <body>
            <form method="post" action="/fileupload" enctype="multipart/form-data">
              <input type="file" name="file" /><br /><br />
              <button type="submit">Upload to server</button>
            </form>
          </body>
          </html>''';
  });
```
