### ISSUE TITLE
Youtube Tutorials

### ISSUE THREAD

**Issue by rohitsangwan01** [rknell/alfred#78]
Hey , Great Package , Specially for Flutter Developers , It would be really great if you can provide some tutorials on Youtube , as Video Tutorials attract most of the beginners , and easy to understand too ,Really Hope this will grow like Node/Express , and people can really become full Stack with just Dart, also a native support for databases will be really great ,specially Mongo with something like Mongoose , and also support like Passport or something with authrization and authntications within package , that would be really Great

**Comment by rknell** [comment]
Hey @rohitsangwan01 

Agree I would love to make some youtube videos but unfortunately it comes down to a time thing at the moment. I've just started a new business and its eating up all my time and energy. However if the community has any good resources they have made I am very happy to link them.

In regards to the deep database integration though its something I'm not going to add to alfred. Just as express doesn't integrate mongoose - its a separate project - I don't want Alfred to lock into, or at the very least spread resources, too thin. Previous dart webserver packages all tried adding a database layer and they became very heavy as a result.

However I can report that mongo for dart works excellently and you can use it seamlessly with alfred as it is, also I have found that I can write some basic classes that operate in a similar way to mongoose - Usually I create a DatabaseCollection class which is extended by your models. The models use JSON serializable to create toJSON and fromJSON functions and in the database collection class you implement a save, find and byId function. It probably sounds more complex reading this than it is, but it does a surprisingly good job. Its not perfect enough to open source yet though but might do it in the future as a separate project.

The same with Passport really. Personally I use JWTs and create a middleware that says 'isAuthenticated' which adds a user object to the request store so you don't have to call the user twice, but passport is again something I would want to be a separate project.

If the community builds any of these things I would be very happy to link them too. My advice though is to just give it a go as it is, you might be surprised just how little extra you need as darts type system solves a lot of what mongoose provides and rolling your own auth middleware is pretty easy, just pick a standard.

**Comment by rknell** [comment]
You asked and it happened!

https://www.youtube.com/playlist?list=PLkEq83S97rEWsgFEzwBW2pxB7pRYb9wAB

**Comment by rohitsangwan01** [comment]
Great , Thank you ✌️
