### ISSUE TITLE
Improve modularization

### ISSUE THREAD

**Issue by felixblaschke** [rknell/alfred#8]
I reviewed your implementation. As I understood from your posting you want a very modular approach on a backend framework.

I recommend adding a generic "add route" method that's getting used by extension methods `get(), post(), patch(), delete()...`. (And optionally making the route matching algorithm exchangeable)

Also the static file serving can be implemented as a "regular route". Currently it's very hardwired into the core.

This pattern opens up Alfred for 3rd party modulare extension and leads to an open design.

**Comment by rknell** [comment]
Upcoming version handles wildcards in the routes better, which allows me to just return a Directory and handle that.

All type handlers are now a "TypeHandler", which is an array you loop over which matches. You can now add a type handler for any dart return type.

v0.1.0
