### ISSUE TITLE
"File uploads example" complain about mismatched arguments: function 'toJson'

### ISSUE THREAD

**Issue by paulscliu** [rknell/alfred#80]
I add the following to the "File upload example"
*************************************
app.get('/html', (req, res) {
    res.headers.contentType = ContentType.html;
    return '''<html>
          <head>
            <title>Image Upload Server</title>
          </head>
          <body>
            <form method="post" action="/upload" enctype="multipart/form-data">
              <input type="file" name="upload" /><br /><br />
              <button type="submit">Upload to server</button>
            </form>
          </body>
          </html>''';
  });

***********************
I got the the following message and upload failed
++++++++++++++++++++++++++++
22-01-20 16:55:15.033229 - error - NoSuchMethodError: Closure call with mismatched arguments: function 'toJson'
Receiver: Closure: (HttpRequest, HttpResponse) => Future<Map<String, String>>
Tried calling: toJson
Found: toJson(HttpRequest, HttpResponse) => Future<Map<String, String>>
2022-01-20 16:55:15.033698 - error - #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:68:5)
#1      serializableTypeHandler.<anonymous closure> (package:alfred/src/type_handlers/serializable_type_handler.dart:9:19)
#2      TypeHandler.handler (package:alfred/src/type_handlers/type_handler.dart:10:15)
#3      Alfred._handleResponse (package:alfred/src/alfred.dart:423:29)
#4      Alfred._incomingRequest (package:alfred/src/alfred.dart:344:17)
<asynchronous suspension>
#5      _QueuedFuture.execute (package:queue/src/dart_queue_base.dart:26:16)
<asynchronous suspension>
++++++++++++++++++++++++++++++++++

Any suggestion on what I did wrong?

**Comment by d-markey** [comment]
I'm not sure what you're trying to achieve with this code... I tried it and when pointing the browser to `http://localhost:port/html`, it correctly displays your document (which is not HTML btw).

If you're trying to upload files, you need to use `app.post()` to accept incoming POST requests. And you need a Web page with an upload form or something like that.

**Comment by paulscliu** [comment]
Here is the complete listing of the code that I tried:
++++++++++++++++++++++++++
import 'dart:io';

import 'package:alfred/alfred.dart';

void main() async {
  final app = Alfred();

  app.get('/example', (req, res) => 'Hello world');

  app.get('/html', (req, res) {
    res.headers.contentType = ContentType.html;
    return '''<html>
          <head>
            <title>Image Upload Server</title>
          </head>
          <body>
            <form method="post" action="/upload" enctype="multipart/form-data">
              <input type="file" name="upload" /><br /><br />
              <button type="submit">Upload to server</button>
            </form>
          </body>
          </html>''';
  });

  final _uploadDirectory = Directory('uploadedFiles');

  app.post(
      '/upload',
      (req, res) => (HttpRequest req, HttpResponse res) async {
            final body = await req.bodyAsJsonMap;

            // Create the upload directory if it doesn't exist
            if (await _uploadDirectory.exists() == false) {
              await _uploadDirectory.create();
            }

            // Get the uploaded file content
            final uploadedFile = (body['file'] as HttpBodyFileUpload);
            var fileBytes = (uploadedFile.content as List<int>);

            // Create the local file name and save the file
            await File('${_uploadDirectory.absolute}/${uploadedFile.filename}')
                .writeAsBytes(fileBytes);

            /// Return the path to the user
            ///
            /// The path is served from the /files route above
            return ({
              'path':
                  'https://${req.headers.host ?? ''}/files/${uploadedFile.filename}'
            });
          });

  await app.listen();
}
+++++++++++++++++++++++

After I uploaded the file, I got the error message about toJson method.

**Comment by paulscliu** [comment]
I did use the post function in the code. This is the complete listing of the code that I tried.

https://gist.github.com/paulscliu/4ed11b67b4a9dd6f9eb5dbbebcf811b3.js

After I selected the file and pressed the upload button, I get the error message about the toJson error message.

**Comment by paulscliu** [comment]
Thanks for the reply. I did use the post function in the code. This is the complete listing of the code that I tried.

https://gist.github.com/paulscliu/4ed11b67b4a9dd6f9eb5dbbebcf811b3

After I selected the file and pressed the upload button, I get the error message about the toJson error message.

**Comment by d-markey** [comment]
Hello, there are several problems in the code:

1. the POST handler returns a closure because of:

```
app.post(
      '/fileupload',
      (req, res) => (HttpRequest req, HttpResponse res) async {
```

The code should read:

```
app.post(
      '/fileupload',
      (req, res) async {
```

2. There a mismatch between your HTML form (the file is named "fileupload") and your POST handler (it expects a "file" entry in the incoming request):

```
<input type="file" name="fileupload" /><br /><br />
```
and
```
final uploadedFile = (body['file'] as HttpBodyFileUpload);
```

Make sure both handlers refer to the same name (either `file` or `fileupload`).

3. When building the path to save the file `File('${_uploadDirectory.absolute}/${uploadedFile.filename}')` : `{_uploadDirectory.absolute` returns a `Directory` and it does not play well when Dart interpolates the string. You should tr `File('${_uploadDirectory.absolute.path}/${uploadedFile.filename}')`

**Comment by paulscliu** [comment]
Thanks a lot. That really helps.
