### ISSUE TITLE
Developer experience

### ISSUE THREAD

**Issue by JannieT** [rknell/alfred#84]
I am super excited to come across this project and last night I have converted one of my PHP backend services over to Alfred with minimum effort. So first: THANK YOU.

Very noob question: what is the normal developer workflow? Can folders be watched and re-compiled while the server is running? Looks like one has to Ctrl-C and restart the server any time you want to inspect the result of a code change.

**Comment by rknell** [comment]
Hi Jannie,

At the moment, yeah its a restart. I tend to use Android studio for development, it has a handy run feature and also a debug button which allows you to put in breakpoints and inspect the code. I think visual studio code has the same but that would be someone else's domain. I tend to stay away from just running it from the command line, however an automatic restart feature is something I would happily look into in the future.
