### ISSUE TITLE
hot reload?

### ISSUE THREAD

**Issue by kumamoto** [rknell/alfred#96]
wondering how to get that to work with dart, should be possible...?

**Comment by tomassasovsky** [comment]
Hey @kumamoto! I highly recommend looking into the [pkg:vm_service](https://pub.dev/packages/vm_service), which handles the hot reload, and you can adapt it to your needs from there.

If you're looking for a simplified version, you could use the [pkg:recharge](https://pub.dev/packages/recharge).

**Comment by rknell** [comment]
thanks @tomassasovsky. Going to close this for now
