### ISSUE TITLE
Need example of using websocket

### ISSUE THREAD

**Issue by bubnenkoff** [rknell/alfred#97]
Hello, I decided to ask on SO because here is low activity https://stackoverflow.com/questions/72733796/how-to-add-to-websocket-response-some-additional-information

But I want to put link here, maybe anybody could help me and provide addition example of using websocket.

**Comment by rknell** [comment]
Ok, so Alfred uses the websocket class from Dart:IO - its not something we have developed so anything you can find on that will apply to Alfred.

https://api.dart.dev/be/180361/dart-io/WebSocket-class.html

Here is a tutorial that just uses pure dart and strips away all the complexity of alfred or flutter, and just connects and sends messages:
https://medium.com/flutter-community/working-with-sockets-in-dart-15b443007bc9

There is a small example of using it here if you haven't found it yet:
https://github.com/rknell/alfred/tree/master/example/example_websocket

So I don't have time to dig into making a full example right now, but I am assuming the trick to broadcasting a message to all clients (as per your SO question) `data for every user to client. For example (let's simplify) it's country from server. For example I have next map:` `is to loop over each client and send something`. I can't see a proper broadcast method though this probably exists.

So when someone connects, add the websocket to a set.
When someone disconnects, remove the websocket from the set.
When you want to broadcast, loop over the set and send a message to each websocket. This is probably a good use case for  https://github.com/rknell/dart_queue so you can do it super quickly without flooding a connection, but that may not be necessary.

I'll close it for now, but feel free to hit me up on this thread and I'll reopen it if necessary.
