### ISSUE TITLE
[Question] It's possible to run alfred on Android?

### ISSUE THREAD

**Issue by mileo** [rknell/alfred#99]
Hi,

It's possible to run alfred on Android? To provide a REST API, to inter app communication? or External?

For example:

![image](https://user-images.githubusercontent.com/1975978/177409063-bf8217c1-b1e3-4f9a-866a-6990e264835e.png)

Source: https://docs.adyen.com/point-of-sale/choose-your-architecture/local

**Comment by rknell** [comment]
Not only is it possible - literally yesterday I wrote a small app that uses the phone as a server and then allows me to hit the Alfred API on the phone to send bulk SMS messages. It worked perfectly with no additional considerations.
